#!/bin/bash
# This script calculates the change due to met and et shifts


echo "+++++++++++++++++++++++++++++++++++++++++"
echo "		compare M_T							"
echo "+++++++++++++++++++++++++++++++++++++++++"
echo "\n No shifts"
python analyse.py -q --save
echo""
echo "\n E_T up"
python analyse.py -q --datafile "d0_new2met0.root/MessTree"
echo "\n E_T down"
python analyse.py -q --datafile "d0_new-2met0.root/MessTree"
echo "\n MET up"
python analyse.py -q --datafile "d0_new0met2.root/MessTree"
echo "\n MET down"
python analyse.py -q --datafile "d0_new0met-2.root/MessTree"
echo "el_et>35 && met>30"
python analyse.py -q  -c "el_et>35 && met>30"
echo "el_et>25 && met>30"
python analyse.py -q  -c "el_et>25 && met>30"
echo "el_et>30 && met>35"
python analyse.py -q  -c "el_et>30 && met>35"
echo "el_et>30 && met>25"
python analyse.py -q  -c "el_et>30 && met>25"

echo "+++++++++++++++++++++++++++++++++++++++++"
echo "		compare E_T							"
echo "+++++++++++++++++++++++++++++++++++++++++"
echo "No shifts"
python analyse.py -p el_et -q --save
echo "\n E_T up"
python analyse.py -q -p el_et --datafile "d0_new2met0.root/MessTree"
echo "\n E_T down"
python analyse.py -q -p el_et --datafile "d0_new-2met0.root/MessTree"
echo "\n MET up"
python analyse.py -q -p el_et --datafile "d0_new0met2.root/MessTree"
echo "\n MET down"
python analyse.py -q -p el_et --datafile "d0_new0met-2.root/MessTree"
echo "el_et>35 && met>30"
python analyse.py -q -p el_et -c "el_et>35 && met>30"
echo "el_et>25 && met>30"
python analyse.py -q -p el_et -c "el_et>25 && met>30"
echo "el_et>30 && met>35"
python analyse.py -q -p el_et -c "el_et>30 && met>35"
echo "el_et>30 && met>25"
python analyse.py -q -p el_et -c "el_et>30 && met>25"

